### ISSUE TITLE
where does port 90 come from?

### ISSUE THREAD

**Issue by briteming** [Egregors/socks5-server#4]
hi.

root@umh:~# /root/go/gopath/bin/socks5-server
2018/08/24 13:03:09 SOCKS5 server: https://github.com/Egregors/socks5-server
2018/08/24 13:03:09 Configuration..
2018/08/24 13:03:09 Starting server on 0.0.0.0:90

i checked https://github.com/Egregors/socks5-server/blob/master/s5.go ,found no port 90.

**Comment by egregors** [comment]
hi, @briteming 

Looks strange. I'll check ASAP

**Comment by egregors** [comment]
@briteming please check your ENV, looks like you already have "PORT" variable with value "90". 

by default, if you don't have "PORT" var in ENV, the server will start on 1080 port. (see `s5.go:15`)
